/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '00-Algorithm'}],
  tutorialSidebar2: [{type: 'autogenerated', dirName: '01-Data-structure'}],
  tutorialSidebar3: [{type: 'autogenerated', dirName: '02-Database'}],
  tutorialSidebar4: [{type: 'autogenerated', dirName: '03-Network'}],
  tutorialSidebar5: [{type: 'autogenerated', dirName: '04-AWS'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
